import type { NextPage } from "next";
import Head from "next/head";
import { NextRouter, useRouter } from "next/router";

type CardProps = {
  name: string;
  description: string;
  link: string;
  router: NextRouter;
};

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Farm Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-green-600">
          Farm Manager
        </h1>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <Card
            name="Mowing"
            description="Mowing records"
            link="/mowing"
            router={router}
          />
        </div>
      </main>
    </>
  );
};

const Card = ({
  name,
  description,
  link,
  router,
}: CardProps) => {
  return (
    <section 
      onClick={() => router.push(link)}
      className="flex flex-col justify-center p-6 duration-500 border-2 border-green-500 rounded shadow-xl motion-safe:hover:scale-105 cursor-pointer">
      <h2 className="text-3xl text-green-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
    </section>
  );
};

export default Home;
